`define width_cmd 0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1+1+1+1+1+`iq_addr_width
`define type_cmd(x) [0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1+1+1+1+1+`iq_addr_width-1:0] x
`define form_cmd [0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1+1+1+1+1+`iq_addr_width-1:0]
`define ref_cmd_valid(x)  x[0+1-1:0]
`define cmd_valid(x) `ref_cmd_valid(x)
`define ref_cmd_is_jump(x)  x[0+1+1-1:0+1]
`define cmd_is_jump(x) `ref_cmd_is_jump(x)
`define ref_cmd_opcode(x)  x[0+1+1+`opcode_width-1:0+1+1]
`define cmd_opcode(x) `ref_cmd_opcode(x)
`define ref_cmd_rs1_addr(x)  x[0+1+1+`opcode_width+`reg_addr_width-1:0+1+1+`opcode_width]
`define cmd_rs1_addr(x) `ref_cmd_rs1_addr(x)
`define ref_cmd_rs2_addr(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width-1:0+1+1+`opcode_width+`reg_addr_width]
`define cmd_rs2_addr(x) `ref_cmd_rs2_addr(x)
`define ref_cmd_dep1(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width]
`define cmd_dep1(x) `ref_cmd_dep1(x)
`define ref_cmd_dep2(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width]
`define cmd_dep2(x) `ref_cmd_dep2(x)
`define ref_cmd_imm(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width]
`define cmd_imm(x) `ref_cmd_imm(x)
`define ref_cmd_value(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width]
`define cmd_value(x) `ref_cmd_value(x)
`define ref_cmd_a1_use_reg(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width]
`define cmd_a1_use_reg(x) `ref_cmd_a1_use_reg(x)
`define ref_cmd_a1_use_dep(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1]
`define cmd_a1_use_dep(x) `ref_cmd_a1_use_dep(x)
`define ref_cmd_a2_use_reg(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1]
`define cmd_a2_use_reg(x) `ref_cmd_a2_use_reg(x)
`define ref_cmd_a2_use_dep(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1]
`define cmd_a2_use_dep(x) `ref_cmd_a2_use_dep(x)
`define ref_cmd_a2_use_imm(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1]
`define cmd_a2_use_imm(x) `ref_cmd_a2_use_imm(x)
`define ref_cmd_rd_addr(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1]
`define cmd_rd_addr(x) `ref_cmd_rd_addr(x)
`define ref_cmd_reg_we(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width]
`define cmd_reg_we(x) `ref_cmd_reg_we(x)
`define ref_cmd_mem_re(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1]
`define cmd_mem_re(x) `ref_cmd_mem_re(x)
`define ref_cmd_mem_we(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1]
`define cmd_mem_we(x) `ref_cmd_mem_we(x)
`define ref_cmd_npc(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1]
`define cmd_npc(x) `ref_cmd_npc(x)
`define ref_cmd_pred_npc(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width]
`define cmd_pred_npc(x) `ref_cmd_pred_npc(x)
`define ref_cmd_beqz(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width]
`define cmd_beqz(x) `ref_cmd_beqz(x)
`define ref_cmd_bnez(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1+1-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1]
`define cmd_bnez(x) `ref_cmd_bnez(x)
`define ref_cmd_jmp(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1+1+1-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1+1]
`define cmd_jmp(x) `ref_cmd_jmp(x)
`define ref_cmd_jr(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1+1+1+1-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1+1+1]
`define cmd_jr(x) `ref_cmd_jr(x)
`define ref_cmd_jal(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1+1+1+1+1-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1+1+1+1]
`define cmd_jal(x) `ref_cmd_jal(x)
`define ref_cmd_iq_pos(x)  x[0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1+1+1+1+1+`iq_addr_width-1:0+1+1+`opcode_width+`reg_addr_width+`reg_addr_width+`iq_addr_width+`iq_addr_width+`imm_width+`value_width+1+1+1+1+1+`reg_addr_width+1+1+1+`pc_width+`pc_width+1+1+1+1+1]
`define cmd_iq_pos(x) `ref_cmd_iq_pos(x)
