`define nrst        `global_nrst(ctl_bus)
`define clk         `global_clk(ctl_bus)
`define iq_head     `global_head(ctl_bus)
`define iq_tail     `global_tail(ctl_bus)
`define headbit     `global_headbit(ctl_bus)
`define tailbit     `global_tailbit(ctl_bus)
`define flushbit    `global_flushbit(ctl_bus)
`define commitbit   `global_commitbit(ctl_bus)
`define insertbit   `global_insertbit(ctl_bus)
`define flush       (`flushbit != 0)
